name: Deploy server

on:
  push:
    branches:
      - master
    paths:
      - server/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "if-biolog"
          heroku_email: "juanbelieni@gmail.com"
          appdir: "server"
